### ISSUE TITLE
请问考虑支持hyperf2吗

### ISSUE THREAD

**Issue by shangeyao** [wilbur-yu/hyperf-soar#1]
Problem 1
    - wilbur/hyperf-soar dev-master requires hyperf/config 1.1.* -> found hyperf/config[v1.1.0, ..., 1.1.x-dev] but it conflicts with your root composer.json require (2.1.*).
    - Root composer.json requires wilbur/hyperf-soar 9999999-dev -> satisfiable by wilbur/hyperf-soar[].

**Comment by wenber-yu** [comment]
更新了.
