### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by shangeyao** [wilbur-yu/hyperf-soar#2]
如下错误：
[WARNING] TypeError: Argument 1 passed to Wilbur\HyperfSoar\Aspect\ResponseAspect::getScore() must be of the type string, null given, called in /Users/shangeyao/PhpstormProjects/orders/runtime/container/proxy/Wilbur_HyperfSoar_Aspect_ResponseAspect.proxy.php on line 106(0) in /Users/shangeyao/PhpstormProjects/orders/runtime/container/proxy/Wilbur_HyperfSoar_Aspect_ResponseAspect.proxy.php:85
Stack trace:
#0 /Users/shangeyao/PhpstormProjects/orders/runtime/container/proxy/Wilbur_HyperfSoar_Aspect_ResponseAspect.proxy.php(106): Wilbur\HyperfSoar\Aspect\ResponseAspect->getScore(NULL)
#1 /Users/shangeyao/PhpstormProjects/orders/runtime/container/proxy/Wilbur_HyperfSoar_Aspect_ResponseAspect.proxy.php(75): Wilbur\HyperfSoar\Aspect\ResponseAspect->formatting('[\n {\n  "ID": "1...')
#2 /Users/shangeyao/PhpstormProjects/orders/vendor/hyperf/utils/src/Functions.php(271): Wilbur\HyperfSoar\Aspect\ResponseAspect->Wilbur\HyperfSoar\Aspect\{closure}()
#3 /Users/shangeyao/PhpstormProjects/orders/vendor/hyperf/utils/src/Coroutine.php(62): call(Object(Closure))
#4 {main}
PHP Warning:  Illegal string offset 'Severity' in /Users/shangeyao/PhpstormProjects/orders/runtime/container/proxy/Wilbur_HyperfSoar_Aspect_ResponseAspect.proxy.php on line 106
PHP Warning:  array_merge(): Expected parameter 1 to be an array, string given in /Users/shangeyao/PhpstormProjects/orders/runtime/container/proxy/Wilbur_HyperfSoar_Aspect_ResponseAspect.proxy.php on line 107
PHP Warning:  Illegal string offset 'Severity' in /Users/shangeyao/PhpstormProjects/orders/runtime/container/proxy/Wilbur_HyperfSoar_Aspect_ResponseAspect.proxy.php on line 106
PHP Warning:  array_merge(): Expected parameter 1 to be an array, string given in /Users/shangeyao/PhpstormProjects/orders/runtime/container/proxy/Wilbur_HyperfSoar_Aspect_ResponseAspect.proxy.php on line 107
PHP Notice:  Trying to access array offset on value of type int in /Users/shangeyao/PhpstormProjects/orders/runtime/container/proxy/Wilbur_HyperfSoar_Aspect_ResponseAspect.proxy.php on line 106

我的配置：
'enabled' => env('SOAR_ENABLED', env('APP_ENV') === 'dev'),
'-soar-path' => env('SOAR_PATH', '/Users/shangeyao/go/src/github.com/XiaoMi/soar/bin/soar'), // soar 二进制文件存储路径
'-test-dsn' => [
    'host' => env('SOAR_TEST_DSN_HOST', '192.168.0.5'),
    'port' => env('SOAR_TEST_DSN_PORT', '3306'),
    'dbname' => env('SOAR_TEST_DSN_DBNAME', 'orders'),
    'username' => env('SOAR_TEST_DSN_USER', 'root'),
    'password' => env('SOAR_TEST_DSN_PASSWORD', 'root'),
    'disable' => env('SOAR_TEST_DSN_DISABLE', false),
],
'-sampling' => env('SOAR_SAMPLING', 0), // 是否开启数据采样开关
'-allow-drop-index' => env('SOAR_ALLOW_DROP_INDEX', 1), // 允许输出删除重复索引的建议
'-drop-test-temporary' => env('SOAR_DROP_TEST_TEMPORARY', 1), // 是否清理测试环境产生的临时库表
'-log-output' => BASE_PATH . '/runtime/logs/soar.log',

soar 0.11.0版安装没有问题，命令行执行无误：
bin % echo 'select * from film' | ./soar
logs.BeeLogger.SetLogger: open /Users/shangeyao/go/src/github.com/XiaoMi/soar/bin/soar.log: permission denied
open /Users/shangeyao/go/src/github.com/XiaoMi/soar/bin/soar.log: permission denied
# Query: 687D590364E29465

★ ★ ★ ☆ ☆ 75分

```sql

SELECT  
  * 
FROM  
  film
```

## 最外层 SELECT 未指定 WHERE 条件

* **Item:**  CLA.001

* **Severity:**  L4

* **Content:**  SELECT 语句没有 WHERE 子句，可能检查比预期更多的行(全表扫描)。对于 SELECT COUNT(\*) 类型的请求如果不要求精度，建议使用 SHOW TABLE STATUS 或 EXPLAIN 替代。

## 不建议使用 SELECT * 类型查询

* **Item:**  COL.001

* **Severity:**  L1

* **Content:**  当表结构变更时，使用 \* 通配符选择所有列将导致查询的含义和行为会发生更改，可能导致查询返回更多的数据。

**Comment by wenber-yu** [comment]
有可能soar升级版本将分值字段名改动了, 我测试修复下

**Comment by wenber-yu** [comment]
我刚测试了下, 没有复现出你所描述的问题. soar 版本在0.11.0已经两年了. 我以为是发布了新版本.
`/Users/shangeyao/go/src/github.com/XiaoMi/soar/bin/soar` 这个是否 chmod +x 赋予了执行权限?
